### hello world test
GET http://localhost:8080/demo/hello

### findAll jpa test
GET http://localhost:8080/demo

### save jpa test
POST http://localhost:8080/demo
Content-Type: application/json

{
    "id": 1,
    "name": "test111",
    "password": "wfwf",
    "type": "2",
    "email": "test@test.com"
}

### mybatis cnt test
GET http://localhost:8080/demo/cnt

### querydsl test
GET http://localhost:8080/demo/{{id}}

### redis test
GET http://localhost:8080/redis-test/{{id}}
